name: Jira Copilot PoC
on:
  repository_dispatch:
    types: [jira_ai_trigger]

jobs:
  copilot-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22'

      - name: Install Copilot CLI
        run: npm install -g @github/copilot@latest

      - name: echo event payload
        run: echo "${{ toJson(github.event.client_payload) }}"

      - name: Install MCP Server dependencies
        run: npm install --prefix jira_mcp_server

      - name: Run Copilot
        run: |
          copilot --allow-all-tools \
            --additional-mcp-config @".github/mcp-config.json" \
            --agent "research" \
            -p "$PAYLOAD" \
            --log-dir ".copilot/logs/" --log-level all
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_USER_TOKEN }}
          XDG_CONFIG_HOME: ${{ github.workspace }}
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
          JIRA_URL: "https://jiraeu.epam.com/"
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_PREM }}

      - name: Upload Copilot logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: copilot-logs
          path: .copilot/logs/
          retention-days: 7
