name: Jira Copilot PoC
on:
  repository_dispatch:
    types: [jira_ai_trigger]

jobs:
  copilot-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Copilot CLI
        run: npm install -g @github/copilot@latest

      - name: echo event payload
        run: echo "${{ toJson(github.event.client_payload) }}"

      - name: Generate Hello World with Copilot
        run: |
          echo "TOKEN: $GITHUB_TOKEN"
          echo "Asking Copilot to generate Hello World..."
          copilot -p "create a simple hello world script in python"
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_USER_TOKEN }}
