name: Jira Copilot PoC
on:
  repository_dispatch:
    types: [jira_ai_trigger]

jobs:
  copilot-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22'

      - name: Install Copilot CLI
        run: npm install -g @github/copilot@latest

      - name: echo event payload
        run: echo "${{ toJson(github.event.client_payload) }}"

      - name: Run MCP Atlassian Docker Container
        run: |
          docker run --rm ghcr.io/sooperset/mcp-atlassian:latest

      - name: Generate Hello World with Copilot
        run: |
          echo "TOKEN: $GITHUB_TOKEN"
          echo "CONFIG HOME: $XDG_CONFIG_HOME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Current Directory:"
          ls -la
          echo "Asking Copilot to generate Hello World..."
          copilot -p "create a simple hello world script in python"
        env:
          GITHUB_TOKEN: ${{ secrets.COPILOT_USER_TOKEN }}
          XDG_CONFIG_HOME: ${{ github.workspace }}
